// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: transactions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addBalance = `-- name: AddBalance :exec
UPDATE users
SET balance = balance + $2
WHERE id = $1
`

type AddBalanceParams struct {
	ID      uuid.UUID
	Balance int32
}

func (q *Queries) AddBalance(ctx context.Context, arg AddBalanceParams) error {
	_, err := q.db.ExecContext(ctx, addBalance, arg.ID, arg.Balance)
	return err
}

const deductBalance = `-- name: DeductBalance :exec
UPDATE users
SET balance = balance - $2  
WHERE id = $1
`

type DeductBalanceParams struct {
	ID      uuid.UUID
	Balance int32
}

func (q *Queries) DeductBalance(ctx context.Context, arg DeductBalanceParams) error {
	_, err := q.db.ExecContext(ctx, deductBalance, arg.ID, arg.Balance)
	return err
}

const insertTransaction = `-- name: InsertTransaction :exec
INSERT INTO transactions (sender_id, receiver_id, amount)
VALUES ($1, $2, $3)
`

type InsertTransactionParams struct {
	SenderID   uuid.UUID
	ReceiverID uuid.UUID
	Amount     int32
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) error {
	_, err := q.db.ExecContext(ctx, insertTransaction, arg.SenderID, arg.ReceiverID, arg.Amount)
	return err
}
