linters-settings:
  errcheck:
    check-blank: true
  staticcheck:
    checks: ["all"]
  gocyclo:
    min-complexity: 15

linters:
  enable:
    - errcheck
    - staticcheck
    - gocyclo

issues:
  uniq-by-line: true
  exclude-rules:
    - path: "internal/database"
      linters:
        - errcheck
        - staticcheck
    - path: "_test.go"
      linters:
        - errcheck
        - staticcheck
        - ineffassign
    - path: "handler_send_coins.go"
      linters:
        - errcheck
    - path: "json.go"
      linters:
        - errcheck

output:
  formats:
    - format: colored-line-number

